<footer class="site-footer">
<a class="footer-backtop" href="#top" onclick="window.scrollTo({top:0,behavior:'smooth'});return false;">Back to top</a>
<div class="footer-main"><div class="wrap footer-columns">
<div class="footer-column"><a class="footer-brand-clean" href="<?php echo esc_url(home_url('/'));?>" aria-label="PA MedLog Talent LLC home"><img class="footer-logo" src="<?php echo esc_url(get_template_directory_uri().'/assets/images/logo.png');?>" alt="PA MedLog Talent LLC"></a></div>
<div class="footer-column"><h4>For Organizations</h4><a href="<?php echo esc_url(home_url('/for-employers'));?>">Hire Talent</a><a href="<?php echo esc_url(home_url('/projects'));?>">IT Projects</a><a href="<?php echo esc_url(home_url('/ai-solutions'));?>">AI Solutions</a><a href="<?php echo esc_url(home_url('/training'));?>">Corporate Training</a></div>
<div class="footer-column"><h4>For Professionals</h4><a href="<?php echo esc_url(home_url('/for-candidates'));?>">Candidate Network</a><a href="<?php echo esc_url(home_url('/career-services'));?>">Career Support</a><a href="<?php echo esc_url(home_url('/training'));?>">Training</a><a href="<?php echo esc_url(home_url('/resources'));?>">Resources</a></div>
<div class="footer-column"><h4>Company</h4><a href="<?php echo esc_url(home_url('/partners'));?>">Partners</a><a href="<?php echo esc_url(home_url('/industries'));?>">Industries</a><a href="<?php echo esc_url(home_url('/contact'));?>">Contact</a><a href="<?php echo esc_url(home_url('/security-data-handling'));?>">Security & Data</a></div>
</div></div>
<div class="footer-lower"><div class="wrap footer-lower-row"><nav class="footer-legal" aria-label="Legal navigation"><a href="<?php echo esc_url(home_url('/privacy-policy'));?>">Privacy</a><a href="<?php echo esc_url(home_url('/terms-of-use'));?>">Terms</a><a href="<?php echo esc_url(home_url('/cookie-policy'));?>">Cookies</a><a href="<?php echo esc_url(home_url('/accessibility'));?>">Accessibility</a></nav><div class="copyright">© <?php echo date('Y');?> PA MedLog Talent LLC. All rights reserved.</div></div></div>
</footer>
<?php $pamed_ai_ready = function_exists('pamedlog_ai_api_key') && pamedlog_ai_api_key(); ?>
<aside class="kathya-assistant<?php echo $pamed_ai_ready ? '' : ' is-unconfigured'; ?>" aria-label="KATHYA website assistant">
<button class="kathya-launcher" type="button" aria-expanded="false" aria-controls="kathya-panel" aria-label="Open KATHYA assistant"><span class="online-dot" aria-hidden="true"></span><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M7 18l-4 3v-5a8 8 0 1 1 4 2Z"/><path d="M8 10h.01M12 10h.01M16 10h.01"/></svg></button>
<section id="kathya-panel" class="kathya-panel" aria-hidden="true" aria-label="KATHYA Assistant chat">
<div class="kathya-head"><div class="kathya-avatar" aria-hidden="true">K</div><div class="kathya-head-copy"><strong>KATHYA Assistant</strong><small<?php echo $pamed_ai_ready ? '' : ' class="ai-pending"'; ?>><?php echo $pamed_ai_ready ? 'Online · Generative AI' : 'AI setup in progress'; ?></small></div><button class="kathya-close" type="button" aria-label="Close assistant">×</button></div>
<?php if(!$pamed_ai_ready): ?><div class="kathya-setup-note">Live AI is not configured yet. You can still use the website links below, or contact our team from the Contact page.</div><?php endif; ?>
<div class="kathya-messages" aria-live="polite"><div class="kathya-message bot"><?php echo $pamed_ai_ready ? 'Hi! I’m the PA MedLog website assistant. What can I help you find?' : 'KATHYA live AI is being configured. Choose an option below to continue.'; ?></div><div class="kathya-quick"><button type="button" data-kathya-link="/for-employers">Hire talent</button><button type="button" data-kathya-link="/for-candidates">Career support</button><button type="button" data-kathya-link="/projects">IT project</button><button type="button" data-kathya-link="/ai-solutions">AI solutions</button><button type="button" data-kathya-link="/training">Training</button></div></div>
<form class="kathya-compose"><div class="kathya-input-row"><input class="kathya-input" type="text" maxlength="240" autocomplete="off" placeholder="<?php echo $pamed_ai_ready ? 'Ask about our services…' : 'Live AI setup in progress'; ?>" aria-label="Message KATHYA Assistant" <?php disabled(!$pamed_ai_ready); ?>><button class="kathya-send" type="submit" aria-label="Send message" <?php disabled(!$pamed_ai_ready); ?>>→</button></div><small class="kathya-disclaimer"><?php echo $pamed_ai_ready ? 'AI-generated guidance may be inaccurate. Avoid sharing sensitive information. For account or project-specific matters, contact our team.' : 'Live generative AI will become available after secure server-side configuration.'; ?></small></form>
</section></aside>
<?php wp_footer();?><script>document.addEventListener('DOMContentLoaded',function(){var b=document.querySelector('.nav-toggle'),n=document.querySelector('.site-header nav');if(!b||!n)return;function closeMenu(){n.classList.remove('is-open');b.setAttribute('aria-expanded','false');b.setAttribute('aria-label','Open navigation');}b.addEventListener('click',function(){var o=n.classList.toggle('is-open');b.setAttribute('aria-expanded',o?'true':'false');b.setAttribute('aria-label',o?'Close navigation':'Open navigation');});n.addEventListener('click',function(e){if(e.target.closest('a'))closeMenu();});document.addEventListener('keydown',function(e){if(e.key==='Escape')closeMenu();});window.addEventListener('resize',function(){if(window.innerWidth>860)closeMenu();});});</script></body></html>