<?php get_header(); ?>
<main>
<section class="hero"><div class="wrap hero-grid"><div><span class="eyebrow">People • AI • Future</span><h1 class="hero-title"><span class="hero-title-main">Connecting people, technology</span><span class="hero-title-accent">&amp; opportunities.</span></h1><p>PA MedLog Talent LLC helps organizations hire technology talent, deliver AI and IT initiatives, and build workforce capability—while helping professionals strengthen skills and career readiness.</p><div class="hero-actions"><a class="btn btn-primary" href="<?php echo esc_url(home_url('/for-employers'));?>">Find Talent →</a><a class="btn btn-outline" href="<?php echo esc_url(home_url('/for-candidates'));?>">Find Opportunities</a><a class="btn btn-outline" href="<?php echo esc_url(home_url('/projects'));?>">Build With Us</a></div><div class="stat-row"><div class="stat"><strong>Talent</strong><span>Staffing & teams</span></div><div class="stat"><strong>Technology</strong><span>AI & IT delivery</span></div><div class="stat"><strong>Training</strong><span>Workforce capability</span></div></div></div><div class="hero-art premium-visual" aria-label="PA MedLog solutions overview"><div class="visual-orbit"><span class="orbit-dot dot-a"></span><span class="orbit-dot dot-b"></span><span class="orbit-dot dot-c"></span><div class="visual-core"><span class="visual-kicker">PA MEDLOG</span><strong>People + AI + Technology</strong><small>One connected delivery ecosystem</small></div><div class="visual-card visual-card-a"><span><?php pamed_icon('users');?></span><div><b>Talent</b><small>Specialist teams</small></div></div><div class="visual-card visual-card-b"><span><?php pamed_icon('sparkles');?></span><div><b>AI</b><small>Agents & automation</small></div></div><div class="visual-card visual-card-c"><span><?php pamed_icon('code');?></span><div><b>Technology</b><small>Build & modernize</small></div></div></div></div></div></section>

<section class="section" id="start"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Start here</span><h2>One company. Clear paths.</h2></div><p>Choose the outcome you need instead of navigating a long list of services.</p></div><div class="audience-split"><article class="audience-card"><span class="mini-label">For organizations</span><h3>Build the team or technology your roadmap requires.</h3><p>Hire specialist talent, launch a technology project, automate workflows with AI, or train your team.</p><div class="hero-actions"><a class="btn btn-primary" href="<?php echo esc_url(home_url('/for-employers'));?>">For Employers →</a><a class="btn btn-outline" href="<?php echo esc_url(home_url('/projects'));?>">Start a Project</a></div></article><article class="audience-card"><span class="mini-label">For professionals</span><h3>Build a stronger technology career.</h3><p>Join the candidate network, improve career readiness, develop practical skills and explore relevant resources.</p><div class="hero-actions"><a class="btn btn-primary" href="<?php echo esc_url(home_url('/for-candidates'));?>">For Candidates →</a><a class="btn btn-outline" href="<?php echo esc_url(home_url('/training'));?>">Explore Training</a></div></article></div></div></section>

<section class="section alt"><div class="wrap"><div class="section-head"><div><span class="eyebrow">What we do</span><h2>Talent + technology + training.</h2></div><p>Focused capabilities that can work independently or together.</p></div><div class="capability-grid"><article class="capability-card"><div class="icon"><?php pamed_icon('users');?></div><h3>Talent Solutions</h3><p>Contract, contract-to-hire, direct hire, staff augmentation and project teams.</p></article><article class="capability-card"><div class="icon"><?php pamed_icon('sparkles');?></div><h3>AI & Automation</h3><p>AI voice agents, conversational AI, workflow automation and business integrations.</p></article><article class="capability-card"><div class="icon"><?php pamed_icon('code');?></div><h3>IT Projects</h3><p>Software, web, cloud, data, integrations and modernization initiatives.</p></article><article class="capability-card"><div class="icon"><?php pamed_icon('graduation');?></div><h3>Training</h3><p>Applied AI, cloud, data, DevOps and workforce upskilling programs.</p></article><article class="capability-card"><div class="icon"><?php pamed_icon('briefcase');?></div><h3>Career Support</h3><p>Professional positioning, interview readiness and structured career guidance.</p></article><article class="capability-card"><div class="icon"><?php pamed_icon('handshake');?></div><h3>Partnerships</h3><p>Technology, delivery, training and responsible business collaboration.</p></article></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Technology expertise</span><h2>Modern capabilities for modern teams.</h2></div><p>Focused across the technology areas employers and delivery teams rely on.</p></div><div class="tech-grid"><article class="tech-card"><span class="mini-label">AI</span><h3>AI & GenAI</h3><p>LLMs, RAG, AI agents, ML engineering and intelligent applications.</p></article><article class="tech-card"><span class="mini-label">Cloud</span><h3>Cloud</h3><p>AWS, Microsoft Azure, Google Cloud and cloud modernization.</p></article><article class="tech-card"><span class="mini-label">Data</span><h3>Data</h3><p>Data engineering, analytics, BI, pipelines and data platforms.</p></article><article class="tech-card"><span class="mini-label">DevOps</span><h3>DevOps</h3><p>CI/CD, containers, Kubernetes, infrastructure and observability.</p></article><article class="tech-card"><span class="mini-label">Software</span><h3>Software Engineering</h3><p>Java, Python, .NET, full stack, APIs and microservices.</p></article><article class="tech-card"><span class="mini-label">Security</span><h3>Cybersecurity</h3><p>Cloud security, IAM, security engineering and compliance support.</p></article><article class="tech-card"><span class="mini-label">Quality</span><h3>QA & Automation</h3><p>Test automation, API testing and quality engineering.</p></article><article class="tech-card"><span class="mini-label">Platforms</span><h3>Enterprise Platforms</h3><p>Salesforce, ServiceNow and adjacent enterprise technologies.</p></article></div></div></section>

<section class="section alt"><div class="wrap"><div class="section-head"><div><span class="eyebrow">How it works</span><h2>Simple, accountable workflows.</h2></div><p>Clear steps for both organizations and professionals.</p></div><h3>For employers</h3><div class="process-line"><div class="process-node"><b>01</b><strong>Submit requirement</strong></div><div class="process-node"><b>02</b><strong>Requirement review</strong></div><div class="process-node"><b>03</b><strong>Source / design</strong></div><div class="process-node"><b>04</b><strong>Screen / validate</strong></div><div class="process-node"><b>05</b><strong>Present solution</strong></div><div class="process-node"><b>06</b><strong>Interview / deliver</strong></div></div><h3 style="margin-top:42px">For candidates</h3><div class="process-line"><div class="process-node"><b>01</b><strong>Submit profile</strong></div><div class="process-node"><b>02</b><strong>Profile review</strong></div><div class="process-node"><b>03</b><strong>Career direction</strong></div><div class="process-node"><b>04</b><strong>Opportunity support</strong></div><div class="process-node"><b>05</b><strong>Interview readiness</strong></div><div class="process-node"><b>06</b><strong>Ongoing guidance</strong></div></div></div></section>

<section class="section"><div class="wrap"><div class="kathya-showcase"><div><span class="eyebrow">KATHYA AI</span><h2>Conversations that get work done.</h2><p>A standalone conversational AI product by PA MedLog Talent LLC for voice-led customer journeys, qualification, support, appointments and workflow automation.</p><div class="hero-actions"><a class="btn btn-primary" href="<?php echo esc_url(home_url('/kathya-ai'));?>">Explore KATHYA AI →</a><a class="btn btn-outline" href="<?php echo esc_url(home_url('/contact'));?>">Request a Demo</a></div></div><div class="voice-ui"><strong>AI Voice Experience</strong><div class="wave"><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="industry-pills"><span>Lead Qualification</span><span>Support</span><span>Appointments</span><span>Multilingual</span></div></div></div></div></section>

<?php pamed_case_highlights('home'); ?>

<section class="section alt"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Articles & Insights</span><h2>Useful ideas, not filler.</h2></div><p>Practical reading across AI, hiring, careers, cloud, data and workforce capability.</p></div><div class="article-grid"><?php $q=new WP_Query(['post_type'=>'post','posts_per_page'=>3]); if($q->have_posts()): while($q->have_posts()):$q->the_post();?><article class="article-card"><span class="mini-label">Insight</span><h3><?php the_title();?></h3><p><?php echo esc_html(get_the_excerpt());?></p><a class="link" href="<?php the_permalink();?>">Read article →</a></article><?php endwhile;wp_reset_postdata();else:?><article class="article-card"><h3>Articles are ready for publishing.</h3><p>Add posts in WordPress Admin → Posts.</p></article><?php endif;?></div><div class="section-action"><a class="btn btn-outline" href="<?php echo esc_url(home_url('/resources'));?>">Explore Resources →</a></div></div></section>

<section class="section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Built for the web</span><h2>Fast, responsive and discoverable.</h2></div><p>SEO-ready, fast, and fully responsive—built for better visibility and a seamless experience on every device.</p></div></div></section>

<section class="section"><div class="wrap"><div class="cta"><div><span class="eyebrow">Next step</span><h2>Tell us what you need.</h2><p>Hiring, project delivery, AI automation, training or career support—start with the path that fits your goal.</p></div><div class="hero-actions"><a class="btn btn-primary" href="<?php echo esc_url(home_url('/for-employers'));?>">For Employers →</a><a class="btn btn-outline" href="<?php echo esc_url(home_url('/for-candidates'));?>">For Candidates</a></div></div></div></section>
</main>
<?php get_footer(); ?>
