<?php get_header(); while(have_posts()):the_post(); $slug=get_post_field('post_name',get_the_ID()); ?>
<main><?php pamedlog_breadcrumbs(); ?>
<?php if($slug==='projects'): ?>
<section class="page-hero"><div class="wrap"><span class="eyebrow">Projects & Case Studies</span><h1>Work designed around measurable outcomes.</h1><p>Explore published PA MedLog Talent LLC project stories. Case studies are managed from WordPress Admin → Case Studies.</p></div></section>
<section class="section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Case studies</span><h2>Challenges. Solutions. Outcomes.</h2></div><p>Only approved, published case studies appear here.</p></div><div class="grid case-grid"><?php $q=new WP_Query(['post_type'=>'case_study','posts_per_page'=>12]); if($q->have_posts()):while($q->have_posts()):$q->the_post(); $challenge=get_post_meta(get_the_ID(),'case_challenge',true);$solution=get_post_meta(get_the_ID(),'case_solution',true);$outcomes=get_post_meta(get_the_ID(),'case_outcomes',true);?><article class="card"><span class="eyebrow"><?php echo esc_html(get_post_meta(get_the_ID(),'case_industry',true)?:'Case Study');?></span><h3><?php the_title();?></h3><p><strong>Challenge:</strong> <?php echo esc_html(wp_trim_words($challenge,22));?></p><p><strong>Solution:</strong> <?php echo esc_html(wp_trim_words($solution,22));?></p><p><strong>Outcome:</strong> <?php echo esc_html(wp_trim_words($outcomes,22));?></p><a class="link" href="<?php the_permalink();?>">Read case study →</a></article><?php endwhile;wp_reset_postdata();else:?><div class="empty-state"><h3>Case studies ready for your verified project data.</h3><p>We did not invent client names, metrics or outcomes. Add a verified case study in <strong>WordPress Admin → Case Studies → Add New</strong>, complete Challenge, Solution and Outcomes, then publish it.</p></div><?php endif;?></div></div></section>
<section class="section alt"><div class="wrap form-wrap"><div><span class="eyebrow">Start a project</span><h2>Tell us what you want to build.</h2><p>Your submission goes directly into the unified Lead Center.</p></div><?php pamed_form('Start a Project',pamed_basic_fields([['service','Project Type'],['budget','Budget Range'],['timeline','Timeline']]));?></div></section>
<?php elseif($slug==='contact'): ?>
<section class="page-hero"><div class="wrap"><span class="eyebrow">Contact PA MedLog Talent LLC</span><h1>Start the right conversation.</h1><p>General enquiries, careers, candidates and HR: <a href="mailto:hr@pamedlogtalent.com"><strong>hr@pamedlogtalent.com</strong></a></p></div></section>
<section class="section"><div class="wrap form-wrap"><div><h2>General enquiry</h2><p>Share your requirement and we’ll route it to the appropriate team. PA MedLog Talent LLC does not publish a contact phone number on this site.</p></div><?php pamed_form('Contact Inquiry',pamed_basic_fields([['service','Area of Interest',['AI Solutions','IT Project','Hire Talent','Training','Career Support','Partnership','Other']]]),'Send Enquiry →');?></div></section>
<?php elseif($slug==='for-employers'): ?>
<?php pamed_page_intro('For Employers','Build teams, deliver projects and automate operations with one partner.','Share a hiring requirement, technology project, AI workflow or training need. Our model is designed to keep requirements clear and delivery flexible.',['Contract, contract-to-hire & direct hire','Specialized AI, cloud, data, DevOps & software talent','Project teams and staff augmentation','AI voice and workflow automation','Corporate training and upskilling','Clear requirement and delivery workflows']);?>
<section class="section alt"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Choose your path</span><h2>Start with the outcome you need.</h2></div><p>One clear entry point for hiring, delivery, automation and team development.</p></div><div class="option-grid"><a class="option-card" href="#employer-form"><span>01</span><h3>Hire Talent</h3><p>Specialist contract, augmentation or direct-hire requirements.</p></a><a class="option-card" href="<?php echo esc_url(home_url('/projects'));?>"><span>02</span><h3>Deliver a Project</h3><p>Software, cloud, data, AI and automation initiatives.</p></a><a class="option-card" href="<?php echo esc_url(home_url('/ai-solutions'));?>"><span>03</span><h3>Automate with AI</h3><p>Voice agents, conversational AI and workflow automation.</p></a><a class="option-card" href="<?php echo esc_url(home_url('/training'));?>"><span>04</span><h3>Train Your Team</h3><p>Role-based technical and AI capability development.</p></a></div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Employer process</span><h2>From requirement to hire or delivery.</h2></div><p>A structured process keeps expectations, screening and next steps clear.</p></div><div class="process-line"><div class="process-node"><b>01</b><strong>Tell us what you need</strong></div><div class="process-node"><b>02</b><strong>Requirement review</strong></div><div class="process-node"><b>03</b><strong>Source / solution design</strong></div><div class="process-node"><b>04</b><strong>Screen / validate</strong></div><div class="process-node"><b>05</b><strong>Present candidates / plan</strong></div><div class="process-node"><b>06</b><strong>Interview / delivery</strong></div></div></div></section>
<?php pamed_case_highlights('employer');?>
<section id="employer-form" class="section alt"><div class="wrap form-wrap"><div><span class="eyebrow">Employer Requirement</span><h2>What does your organization need?</h2></div><?php pamed_form('Employer Requirement',pamed_basic_fields([['job_type','Requirement Type',['Hiring','Project','AI Automation','Training','Multiple']],['technology','Roles / Skills / Technology'],['timeline','Timeline']]));?></div></section>
<?php elseif($slug==='for-candidates'): ?>
<?php pamed_page_intro('For Candidates','Build a clearer, market-ready professional profile.','We support eligible professionals with career readiness, professional positioning and opportunity support when suitable roles are available. Employment is never guaranteed and employer decisions remain independent.',['Resume & profile positioning','Interview readiness','Job-market guidance','Candidate network registration','Role-alignment support','Professional communication']);?>
<section class="section alt"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Candidate journey</span><h2>A simpler path from profile to opportunity readiness.</h2></div><p>Choose the support that fits where you are today.</p></div><div class="option-grid"><a class="option-card" href="#candidate-form"><span>01</span><h3>Join the Network</h3><p>Register your skills, experience and preferred roles.</p></a><a class="option-card" href="<?php echo esc_url(home_url('/career-services'));?>"><span>02</span><h3>Career Support</h3><p>Strengthen positioning, communication and interview readiness.</p></a><a class="option-card" href="<?php echo esc_url(home_url('/training'));?>"><span>03</span><h3>Build Skills</h3><p>Explore technical and AI learning pathways.</p></a><a class="option-card" href="<?php echo esc_url(home_url('/resources'));?>"><span>04</span><h3>Read Resources</h3><p>Practical articles for careers, AI and the workforce.</p></a></div></div></section>
<section class="section"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Candidate process</span><h2>From profile to opportunity readiness.</h2></div><p>Support is structured around your profile and goals; employment is not guaranteed.</p></div><div class="process-line"><div class="process-node"><b>01</b><strong>Submit profile</strong></div><div class="process-node"><b>02</b><strong>Profile evaluation</strong></div><div class="process-node"><b>03</b><strong>Career recommendations</strong></div><div class="process-node"><b>04</b><strong>Opportunity support</strong></div><div class="process-node"><b>05</b><strong>Interview readiness</strong></div><div class="process-node"><b>06</b><strong>Ongoing guidance</strong></div></div></div></section>
<?php pamed_case_highlights('candidate');?>
<section id="candidate-form" class="section alt candidate-compact"><div class="wrap form-wrap"><div><span class="eyebrow">Candidate Network</span><h2>Join the network.</h2><p>One short profile. All existing information is retained for better role matching.</p></div><?php pamed_form('Candidate Network',pamed_basic_fields([['role','Primary Role / Technology'],['work_auth','Work Authorization'],['experience','Years of Experience'],['resume','Resume (PDF/DOC/DOCX)','file',true]]));?></div></section>
<?php elseif($slug==='resources'): ?>
<?php pamed_page_intro('Resources','Practical guides for AI adoption, hiring, careers and workforce decisions.','Use these resources as starting points for better requirements, stronger professional positioning and more thoughtful technology adoption.',['AI implementation checklist: define use case, handoffs, guardrails and KPIs','Employer requirement checklist: skills, location, employment type and process','Candidate profile checklist: outcomes, tools, projects and concise positioning','Project discovery checklist: users, integrations, security, timeline and ownership']);?>
<section class="section alt"><div class="wrap"><div class="section-head"><div><span class="eyebrow">Articles & Insights</span><h2>AI, hiring, careers and workforce articles</h2></div></div><div class="grid"><?php $q=new WP_Query(['post_type'=>'post','posts_per_page'=>3]);while($q->have_posts()):$q->the_post();?><article class="card"><h3><?php the_title();?></h3><p><?php echo esc_html(get_the_excerpt());?></p><a class="link" href="<?php the_permalink();?>">Read article →</a></article><?php endwhile;wp_reset_postdata();?></div></div></section>
<?php elseif($slug==='partners'): ?>
<?php pamed_page_intro('Partners','Build more value together.','PA MedLog Talent LLC welcomes responsible collaboration with technology providers, implementation specialists, training organizations, service partners and businesses with complementary capabilities.',['Technology and AI integration partnerships','Project delivery collaboration','Training and education partnerships','Referral and business-development collaboration','Specialist delivery partnerships','Co-created solutions with clear ownership']);?>
<section class="section alt"><div class="wrap form-wrap"><div><span class="eyebrow">Partnership Inquiry</span><h2>Tell us how you want to collaborate.</h2></div><?php pamed_form('Partnership Inquiry',pamed_basic_fields([['partnership','Partnership Type']]));?></div></section>
<?php elseif($slug==='industries'): ?>
<section class="page-hero"><div class="wrap"><span class="eyebrow">Industries</span><h1>Technology and workforce capability for complex operating environments.</h1><p>We adapt delivery to the workflows, talent needs and governance expectations of each sector.</p></div></section>
<section class="section"><div class="wrap"><div class="industry-grid">
<?php $inds=[['Technology','AI engineering, software delivery, cloud, data and specialist talent.'],['Healthcare','Technology, operations and workforce support with privacy-aware processes.'],['Financial Services','Data, automation, software and talent solutions aligned to controlled environments.'],['Retail & eCommerce','Digital experiences, automation, analytics and scalable technology talent.'],['Manufacturing','Data, workflow automation, software and engineering capability.'],['Professional Services','AI-enabled operations, project delivery and flexible specialist teams.']];foreach($inds as $i):?><article class="industry-card"><span class="mini-label">Industry</span><h3><?php echo esc_html($i[0]);?></h3><p><?php echo esc_html($i[1]);?></p><a class="link" href="<?php echo esc_url(home_url('/contact'));?>">Discuss a requirement →</a></article><?php endforeach;?></div><p class="proof-note">Capabilities shown are service areas, not claims of client relationships. Published client outcomes appear only in verified case studies.</p></div></section>
<?php elseif($slug==='engagement-models'): ?>
<section class="page-hero"><div class="wrap"><span class="eyebrow">Engagement Models</span><h1>Choose a delivery model that fits the work.</h1><p>Clear scope, ownership and commercial terms help teams move faster with fewer surprises.</p></div></section>
<section class="section"><div class="wrap"><div class="engagement-grid"><?php $mods=[['Fixed Project','Defined scope, milestones and deliverables for a specific technology outcome.'],['Dedicated Team','A focused delivery team aligned to an agreed roadmap and operating cadence.'],['Staff Augmentation','Add specialist capability to an existing team for an agreed period.'],['Contract Talent','Flexible talent support based on role, location and engagement requirements.'],['Direct Hire','Recruitment support for permanent positions where applicable.'],['Corporate Training','Private team programs tailored to role, skill level and business context.']];foreach($mods as $m):?><article class="engagement-card"><span class="mini-label">Model</span><h3><?php echo esc_html($m[0]);?></h3><p><?php echo esc_html($m[1]);?></p></article><?php endforeach;?></div></div></section>
<section class="section alt"><div class="wrap form-wrap"><div><span class="eyebrow">Request scope</span><h2>Tell us what outcome you need.</h2><p>We’ll use your requirement to determine an appropriate engagement structure.</p></div><?php pamed_form('Engagement Inquiry',pamed_basic_fields([['service','Service / Engagement'],['budget','Budget Range'],['timeline','Timeline']]));?></div></section>
<?php elseif(in_array($slug,['security-data-handling','terms-of-use','cookie-policy','accessibility','candidate-privacy-notice'],true)): ?>
<?php $legal=[
'security-data-handling'=>['Security & Data Handling','A practical overview of how website and candidate information should be handled.',['Website forms are intended for ordinary business and career information only.','Visitors should never submit passwords, Social Security numbers, banking credentials or other highly sensitive information.','Candidate documents are stored in a protected server folder for authorized administrative access in this theme.','Keep WordPress, plugins and hosting patched; use MFA, backups, malware scanning and least-privilege administrator access.','Define and document retention/deletion periods before collecting production candidate data.']],
'terms-of-use'=>['Terms of Use','General conditions for use of this website.',['Website content is provided for general informational purposes.','Submitting a form does not create an employment, staffing, consulting or project-delivery agreement.','Employment, project and commercial commitments require separate written agreement.','Users must not misuse the website, upload malicious files or submit information they are not authorized to share.','PA MedLog may update website content and these terms as its services evolve.']],
'cookie-policy'=>['Cookie Policy','A plain-language starting point for website cookie disclosure.',['Essential cookies may be used for core WordPress functionality and security.','Analytics or marketing cookies should only be enabled when the corresponding tools are actually configured.','If non-essential cookies are added, deploy an appropriate consent mechanism for applicable visitors.','Review this policy whenever analytics, advertising, chat or embedded third-party services change.']],
'accessibility'=>['Accessibility','Our goal is a website that is easier for more people to use.',['The theme uses semantic headings, visible focus states and responsive layouts.','Images should include meaningful alternative text when they convey information.','Forms should retain labels and keyboard accessibility when edited.','If you encounter an accessibility barrier, contact hr@pamedlogtalent.com with the page and issue.']],
'candidate-privacy-notice'=>['Candidate Privacy Notice','How candidate information submitted through this website is intended to be used.',['Candidate information is used to review career-support or opportunity-related requests and communicate with the submitter.','Only submit information you are authorized to provide. Do not include SSNs, banking data, passwords or unnecessary sensitive information in resumes.','Resume access should be limited to authorized administrators and relevant recruiting personnel.','Retention periods and deletion procedures should be finalized by PA MedLog before production recruiting at scale.','Candidates may contact hr@pamedlogtalent.com regarding website-submitted candidate information.']]
];$x=$legal[$slug];?>
<section class="page-hero"><div class="wrap"><span class="eyebrow">PA MedLog Talent LLC</span><h1><?php echo esc_html($x[0]);?></h1><p><?php echo esc_html($x[1]);?></p></div></section><section class="section"><div class="wrap legal-copy"><div class="security-callout"><strong>Important:</strong> This website copy is operational guidance, not legal advice. Have counsel review policies for the jurisdictions where PA MedLog operates and collects data.</div><h2>Our approach</h2><ul><?php foreach($x[2] as $li)echo '<li>'.esc_html($li).'</li>';?></ul><h2>Questions</h2><p>For website privacy, accessibility or candidate-data questions, contact <a href="mailto:hr@pamedlogtalent.com">hr@pamedlogtalent.com</a>.</p></div></section>
<?php else: $data=[
'about'=>['About PA MedLog Talent LLC','Technology, talent and AI solutions built around practical business outcomes.','PA MedLog Talent LLC supports organizations and professionals through technology delivery, AI automation, talent solutions and practical training.',['Outcome-first engagements','Clear communication','Flexible delivery models','Responsible AI use','Long-term relationships']],
'services'=>['Services','Build, automate, hire or upskill with a flexible partner.','Our services connect technology execution with workforce capability.',['AI voice agents and conversational AI','Workflow automation','Web, software, cloud and data projects','Talent solutions','Training and upskilling','Employer and candidate support']],
'ai-solutions'=>['AI Solutions','Intelligent conversations and automation that move work forward.','We design AI-powered voice and conversational experiences for practical business workflows. KATHYA AI is a standalone conversational AI product by PA MedLog Talent LLC.',['Inbound and outbound AI voice agents','Lead capture and qualification','Appointment workflows','Customer support automation','CRM integrations','Multilingual experiences','Analytics and summaries','Escalation and guardrails']],
'it-projects'=>['IT Projects','From idea to implementation with flexible technology delivery.','Launch, modernize and integrate digital systems with focused project delivery.',['Web and application development','API and systems integration','Cloud and DevOps','Data engineering and analytics','AI integration','QA and release support','Legacy modernization','Technical discovery']],
'staffing-talent'=>['Staffing & Talent','Connect business needs with qualified, eligible professionals.','We support talent requirements across technology, healthcare, engineering and business functions.',['Contract and direct-hire support','Technology professionals','Healthcare and operations','Engineering functions','Business and analytics roles','Candidate screening']],
'training'=>['Training & Upskilling','Practical learning for real-world application.','Programs for individuals, groups and organizations focus on applied skills and workplace relevance.',['AI and generative AI','Data and analytics','Cloud, DevOps and software','Digital marketing and business tools','Career readiness','Customized workshops']],
'pricing'=>['Pricing','Flexible scope-based engagement.','Pricing depends on service type, scope, timeline, delivery model and required expertise. Request a written proposal for your requirement.',['Project-based pricing','Training cohort pricing','Talent engagement pricing','AI implementation pricing','Custom enterprise proposals']],
'privacy-policy'=>['Privacy Policy','How website enquiries are handled.','Information submitted through website forms is used to respond to enquiries and manage business, candidate, training or partnership requests. Do not submit highly sensitive information through these forms.',['We collect the information you choose to submit','Leads are stored in the WordPress Lead Center','Email notifications are sent to PA MedLog team inboxes','Do not submit passwords, SSNs or banking credentials','Contact hr@pamedlogtalent.com for privacy questions']]
]; $p=$data[$slug]??['PA MedLog Talent LLC','Technology, talent and growth solutions.','We tailor engagements to goals, timelines and operating needs.',['AI and automation','IT project delivery','Talent solutions','Training']]; pamed_page_intro($p[0],$p[1],$p[2],$p[3]); if($slug!=='privacy-policy'): ?>
<section class="section alt"><div class="wrap form-wrap"><div><span class="eyebrow">Get started</span><h2>Tell us about your requirement.</h2></div><?php $type=$slug==='training'?'Training Inquiry':($slug==='ai-solutions'?'AI Solution Inquiry':($slug==='staffing-talent'?'Hire Talent':'General Inquiry')); pamed_form($type,pamed_basic_fields([['service','Service Needed'],['timeline','Timeline']]));?></div></section><?php endif; endif; ?>
</main><?php endwhile; get_footer(); ?>
